from __future__ import annotations

import tkinter as tk
from pathlib import Path
from tkinter import messagebox, ttk


ROOT = Path(__file__).resolve().parent
ENV_PATH = ROOT / ".env"


FIELDS = [
    ("Toss App Key", "TOSS_APP_KEY", "토스증권 Open API Client ID", True),
    ("Toss App Secret", "TOSS_APP_SECRET", "토스증권 Open API Client Secret", True),
    ("DeepSeek API Key", "DEEPSEEK_API_KEY", "Hermes/DeepSeek 분석용 API 키", True),
    ("SEC User-Agent", "SEC_USER_AGENT", "예: stock-agent/0.2 email@example.com", False),
    ("Research Bot Token", "DISCORD_RESEARCH_BOT_TOKEN", "리서치 결과 출력 전용 봇", True),
    ("Critic Bot Token", "DISCORD_CRITIC_BOT_TOKEN", "반론 결과 출력 전용 봇", True),
    ("Chairman Bot Token", "DISCORD_CHAIRMAN_BOT_TOKEN", "슬래시 명령 및 최종결정 봇", True),
    ("Discord Server ID", "DISCORD_GUILD_ID", "세 봇이 들어간 서버 ID", False),
    ("Command Channel ID", "DISCORD_COMMAND_CHANNEL_ID", "사용자 자연어 명령을 받는 유일한 채널", False),
    ("Debate Channel ID", "DISCORD_DEBATE_CHANNEL_ID", "Research/Critic 토론 과정을 게시할 채널", False),
    ("Report Channel ID", "DISCORD_REPORT_CHANNEL_ID", "Chairman 최종 보고서를 게시할 채널", False),
    ("Discord Owner User ID", "DISCORD_OWNER_USER_ID", "명령을 허용할 본인 Discord 사용자 ID", False),
    ("Hermes Model", "HERMES_MODEL", "개발 기본값: deepseek-v4-flash", False),
]


def read_env() -> dict[str, str]:
    values: dict[str, str] = {}
    if ENV_PATH.exists():
        for raw in ENV_PATH.read_text(encoding="utf-8-sig").splitlines():
            if "=" in raw and not raw.lstrip().startswith("#"):
                key, value = raw.split("=", 1)
                values[key.strip()] = value.strip()
    # 이전 단일 봇 설정은 Chairman으로 안전하게 이전합니다.
    if not values.get("DISCORD_CHAIRMAN_BOT_TOKEN") and values.get("DISCORD_BOT_TOKEN"):
        values["DISCORD_CHAIRMAN_BOT_TOKEN"] = values["DISCORD_BOT_TOKEN"]
    legacy_channel = values.get("DISCORD_CHANNEL_ID", "")
    values.setdefault("DISCORD_DEBATE_CHANNEL_ID", legacy_channel)
    values.setdefault("DISCORD_REPORT_CHANNEL_ID", legacy_channel)
    values.setdefault("DISCORD_COMMAND_CHANNEL_ID", legacy_channel)
    return values


def write_env(values: dict[str, str]) -> None:
    merged = read_env()
    merged.update(values)
    merged.pop("DISCORD_BOT_TOKEN", None)
    merged.setdefault("MODE", "PAPER")
    merged.setdefault("MARKET_DATA_PROVIDER", "toss")
    merged.setdefault("LLM_PRIMARY_PROVIDER", "deepseek")
    merged.setdefault("AGENT_PROVIDER", "hermes")
    merged.setdefault("EDGAR_MODE", "live")
    merged.setdefault("HERMES_TRANSPORT", "cli")
    merged.setdefault("HERMES_MODEL", "deepseek-v4-flash")
    merged.setdefault("DATABASE_PATH", "data/stock_agent.db")
    merged.setdefault("OBSIDIAN_VAULT_PATH", "vault/Stock-AI-Vault")
    preferred = [
        "MODE", "MARKET_DATA_PROVIDER", "LLM_PRIMARY_PROVIDER",
        "DATABASE_PATH", "OBSIDIAN_VAULT_PATH", "TOSS_APP_KEY",
        "TOSS_APP_SECRET", "DEEPSEEK_API_KEY", "SEC_USER_AGENT",
        "DISCORD_RESEARCH_BOT_TOKEN", "DISCORD_CRITIC_BOT_TOKEN",
        "DISCORD_CHAIRMAN_BOT_TOKEN", "DISCORD_GUILD_ID",
        "DISCORD_COMMAND_CHANNEL_ID", "DISCORD_OWNER_USER_ID", "DISCORD_ALLOWED_USER_IDS",
        "DISCORD_DEBATE_CHANNEL_ID", "DISCORD_REPORT_CHANNEL_ID", "DISCORD_CHANNEL_ID",
        "AGENT_PROVIDER", "EDGAR_MODE", "HERMES_TRANSPORT", "HERMES_MODEL",
    ]
    keys = preferred + sorted(key for key in merged if key not in preferred)
    lines = ["# Generated by setup_gui.py. Keep this file private."]
    lines.extend(f"{key}={merged.get(key, '')}" for key in keys)
    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    root = tk.Tk()
    root.title("Stock AI Research Agent - API 설정")
    root.geometry("860x920")
    root.minsize(760, 820)

    outer = ttk.Frame(root, padding=20)
    outer.pack(fill="both", expand=True)
    ttk.Label(outer, text="Stock AI Research Agent 설정", font=("Segoe UI", 18, "bold")).pack(anchor="w")
    ttk.Label(
        outer,
        text="입력값은 이 PC의 프로젝트 .env 파일에만 저장됩니다.",
        foreground="#555",
    ).pack(anchor="w", pady=(4, 14))

    form = ttk.Frame(outer)
    form.pack(fill="x")
    env_values = read_env()
    entries: dict[str, ttk.Entry] = {}
    for row, (label, key, hint, secret) in enumerate(FIELDS):
        ttk.Label(form, text=label, width=22).grid(row=row * 2, column=0, sticky="w", pady=(6, 0))
        entry = ttk.Entry(form, width=70, show="●" if secret else "")
        entry.insert(0, env_values.get(key, ""))
        entry.grid(row=row * 2, column=1, sticky="ew", pady=(6, 0))
        ttk.Label(form, text=hint, foreground="#666").grid(row=row * 2 + 1, column=1, sticky="w")
        entries[key] = entry
    form.columnconfigure(1, weight=1)

    notes = ttk.LabelFrame(outer, text="Discord 안내", padding=12)
    notes.pack(fill="x", pady=(16, 12))
    ttk.Label(
        notes,
        text=(
            "세 봇은 같은 Discord 서버에 초대하세요. 별도 서버는 필요 없습니다.\n"
            "Chairman만 명령 채널을 감시하고 Research/Critic은 토론 채널에 출력합니다.\n"
            "Chairman 앱의 Bot 설정에서 Message Content Intent를 켜야 자연어를 읽을 수 있습니다.\n"
            "Research/Critic은 토론 채널에 출력하고 Chairman은 보고서 채널에 최종 결과를 냅니다.\n"
            "각 칸에는 서로 다른 봇 토큰을 입력해야 합니다."
        ),
        justify="left",
    ).pack(anchor="w")

    def save() -> None:
        values = {key: entries[key].get().strip() for _, key, _, _ in FIELDS}
        write_env(values)
        messagebox.showinfo("저장 완료", f"설정이 저장되었습니다.\n{ENV_PATH}")

    buttons = ttk.Frame(outer)
    buttons.pack(fill="x")
    ttk.Button(buttons, text="저장", command=save).pack(side="right")
    ttk.Button(buttons, text="닫기", command=root.destroy).pack(side="right", padx=(0, 8))
    root.mainloop()


if __name__ == "__main__":
    main()
